baseurl: ''
exclude: ['README.md']
permalink: pretty
title: 'dLake'

google_analytics_id: ""
homepage:
  show_call_box: true
logo:
  mobile: "images/logo/logo.png"
  desktop: "images/logo/logo.png"
  desktop_height: "36px"
footer:
  copyright_text: 'Copyright (c) 2021 by Ilya Isakov'

seo:
  meta_og_title: "dLake"
  meta_og_type: "website"
  meta_og_url: "https://dlake.de"
  meta_og_description: "Consulting in information technologies area. Easy digital transformation. Best industrial experience and state-of-the-art solutions at your disposal."

collections:
  services:
    output: true
  team:
    output: true

sass:
  indentWidth: 4
  style: compact # possible values: nested expanded compact compressed
  precision: 10

plugins:
  - jekyll-environment-variables
