baseURL: "https://ci-cloud.de"
title: Cirro Cloud

pagination:
  pagerSize: 8

enableGitInfo: false
pygmentsCodeFences: true
pygmentsCodefencesGuessSyntax: true
pygmentsUseClasses: true
metaDataFormat: yaml
languageCode: de-de
defaultContentLanguage: de
defaultContentLanguageInSubdir: false

params:
  colors:
    # light
    base_bg: "#ffffff"
    base_bg_2: "#f8fafc"
    base_bg_3: "#f1f5f9"
    base_text: "#202020"
    base_text_2: "#4b5563"
    primary_bg: "#2b3af7"
    primary_bg_2: "#424ff8"
    primary_bg_3: "#5150f4"
    primary_text: "#fdfcf9"
    header_text: "#2b3af7"
    logo_text: "#2b3af7"
    hero_gradient: "#1b2bea"
    hero_gradient_2: "#7f2bf7"

    # dark
    base_bg_dark: "#121212"
    base_bg_2_dark: "#1e1e1e"
    base_bg_3_dark: "#232323"
    base_text_dark: "#ffffff"
    base_text_2_dark: "#d7d7d7"
    primary_bg_dark: "#2b8af7"
    primary_bg_dark_2: "#328ffb"
    primary_bg_dark_3: "#4198fd"
    primary_text_dark: "#fdfcf9"
    logo_text_dark: "#ffffff"
    header_text_dark: "#ffffff"
    hero_gradient_dark: "#1b2bea"
    hero_gradient_2_dark: "#7f2bf7"

  fonts:
    use_google_fonts: false
    google_fonts: "https://fonts.googleapis.com/css2?family=Lato:wght@300;400;700&family=Source+Code+Pro&family=Source+Sans+3:wght@300;400;700&display=swap"
    use_self_hosted_fonts: true # font files must be placed in /static/fonts folder and the @font-face definitions must be added to /static/fonts/fonts.css
    logo: "Lato"
    heading: "Lato"
    base: "'Source Sans 3'"
    monospace: "'Source Code Pro'"

  logo:
    logo_text: ""
    logo_image_desktop: images/logo/logo.png
    logo_image_mobile: images/logo/logo-mobile.png
    logo_image_desktop_invert: images/logo/logo-invert.png # used on transparent header and when in dark mode. Normally a white version of the logo.
    logo_image_mobile_invert: images/logo/logo-invert-mobile.png # used on transparent header and when in dark mode. Normally a white version of the logo.
    logo_image_desktop_height: "36px"
    logo_image_desktop_width: "272px"
    logo_image_mobile_height: "30px"
    logo_image_mobile_width: "34px"
    show_logo_image_on_mobile: true
    show_logo_image_on_desktop: true
    show_logo_text_on_mobile: false
    show_logo_text_on_desktop: true
    logo_text_font_size: "24px"
    logo_text_font_weight: "500" # 300, 500, 700

  header:
    fixed: true
    header_height: "60px"
    header_menu_font_size: "18px"

  open_graph:
    og_type: "website"
    og_twitter_card: "summary"
    og_twitter_site: ""
    og_twitter_creator: ""

  dark_mode:
    enable_dark_mode: true
    show_dark_mode_toggle_in_header: false
    show_dark_mode_toggle_in_bottom: true
    show_dark_mode_toggle_in_mobile_menu: true

  cookie_banner:
    enabled: true
    show_manage_cookies_at_bottom: true

  analytics:
    disable_analytics_on_localhost: false # prevents polluting analytics data while developing but enabling can be useful
    google_analytics_id: "G-08T34RNKQB" # G-XXXXXXXXXX
    gtm_id: "GTM-WBF27J36" # GTM-XXXXXXXX
    plausible_data_domain: "" # mywebsite.com
    plausible_script_url: "" # if you use a self-hosted plausible enter the url
    umami_data_website_id: "" # ddd14336-5fb0-4cdd-8f32-e1bfa906cc2b
    umami_src: "" # https://analytics.eu.umami.is/script.js
  
  comments:
    commento:
      enabled: false # you must have a commento account and be on the correct domain. does not work locally.
    disqus:
      shortname: "" # Your disqus shortcode for example "zerostatic". leave this blank ie "" to disable.

  newsletter:
    mailchimp:
      form_action_url: ""
      form_title: "Let's keep in touch"

  contact_form:
    use_netlify_form: false
    use_formspree_form: true
    formspree_endpoint: https://formspree.io/f/mnqeykdg
    netlify_form_name: "contact"

  multilingual:
    enable_language_switcher: false
    show_language_switcher_in_header: false

  menu:
    show_dropdown_items_in_mobile_menu: false
    show_social_media_in_mobile_menu: true

  footer:
    enable_footer: true
    enable_footer_info: true # will show the section with the logo, title and description.
    footer_title: ""
    footer_logo: ""
    footer_logo_height: "32px"
    footer_logo_width: "32px"
    footer_description: ""
    enable_social_media_links: true
    enable_languages: true
    enable_copyright: false
    enable_menu_footer_primary: true
    enable_menu_footer_secondary: true
    enable_menu_footer_tertiary: true
    footer_primary_menu_title: ""
    footer_secondary_menu_title: "Unternehmen"
    footer_tertiary_menu_title: "Sonstiges"

  bottom:
    enabled: true
    enable_bottom_menu: true
    copyright_text: "© 2025 Cirro Cloud GmbH"
    show_rss_icon: true

languages:
  en:
    weight: 1
    languageName: English
    contentDir: content/en
    title: Cirro Cloud
    params:
      footer:
        footer_primary_menu_title: ""
        footer_secondary_menu_title: Company
        footer_tertiary_menu_title: Other
    menu:
      main:
        - name: "Home"
          identifier: home
          url: /
          pageRef: home
          weight: 1
        - name: "Services"
          identifier: services
          url: /services/
          pageRef: services
          weight: 2
#        - name: "Branding"
#          parent: "services"
#          url: "/services/branding"
#          params:
#            icon: "images/icons/icons8-color-palette-100.png"
#        - name: "Our Work"
#          identifier: work
#          url: /work/
#          pageRef: work
#          weight: 2
#        - name: "Blog"
#          identifier: blog
#          url: /blog/
#          pageRef: posts
#          weight: 3
        - name: "Team"
          identifier: team
          url: /team/
          pageRef: team
          weight: 4
        - name: "Contact Us"
          url: /contact/
          weight: 10
          params:
            external: true
            button: true
#      footer_primary:
#        - name: "Services"
#          url: /services/
#          weight: 1
#        - name: "Work"
#          url: /work/
#          weight: 2
      footer_secondary:
        - name: "Home"
          url: /
          pageRef: "home"
          weight: 1
        - name: "Services"
          url: /services/
          pageRef: "services"
          weight: 2
        - name: "Team"
          url: /team/
          pageRef: "team"
          weight: 3
        - name: "Contact"
          url: /contact/
          pageRef: "contact"
          weight: 4
      footer_tertiary:
#        - name: Buy Now
#          url: "https://www.zerostatic.io/theme/hugo-advance/"
#          weight: 1
#          params:
#            external: true
#            button: true
        - name: "Privacy policy"
          url: /privacy/
          pageRef: "privacy"
          weight: 1
        - name: "Impressum"
          url: /impressum/
          pageRef: "impressum"
          weight: 2
      bottom:
        - name: "Impressum"
          url: "/impressum/"
          weight: 1
        - name: "Privacy"
          url: "/privacy/"
          weight: 2

  de:
    weight: 0
    languageName: Deutsch
    contentDir: content/de
    title: Cirro Cloud
    params:
      footer:
        footer_primary_menu_title: ""
        footer_secondary_menu_title: Unternehmen
        footer_tertiary_menu_title: Sonstiges
    menu:
      main:
        - name: "Startseite"
          identifier: home
          url: /
          pageRef: home
          weight: 1
        - name: "Dienstleistungen"
          identifier: services
          url: /services/
          weight: 2
#        - name: "Notre Travail"
#          identifier: work
#          url: /work/
#          weight: 2
#        - name: "Blog"
#          identifier: blog
#          url: /blog/
#          weight: 3
        - name: "Team"
          identifier: team
          url: /team/
          pageRef: team
          weight: 4
        - name: "Kontakt"
          url: /contact/
          weight: 10
          params:
            external: true
            button: true
      footer_primary:
        - name: ""
#          url: /services/
#          weight: 1
#        - name: "Work"
#          url: /work/
#          weight: 2
      footer_secondary:
        - name: "Startseite"
          url: /
          pageRef: "home"
          weight: 1
        - name: "Dienstleistungen"
          url: /services/
          pageRef: "services"
          weight: 2
        - name: "Team"
          url: /team/
          pageRef: "team"
          weight: 3
        - name: "Kontakt"
          url: /contact/
          pageRef: "contact"
          weight: 4
      footer_tertiary:
        - name: "Datenschutz"
          url: /privacy/
          pageRef: "privacy"
          weight: 1
        - name: "Impressum"
          url: /impressum/
          pageRef: "impressum"
          weight: 2
      bottom:
        - name: "Impressum"
          url: "/impressum/"
          weight: 1
        - name: "Datenschutz"
          url: "/privacy/"
          weight: 2

permalinks:
  posts: "blog/:year/:month/:title/"
  pages: ":slug/"

taxonomies:
  tag: tags
  category: categories
  portfolio: portfolio
  author: authors

markup:
  goldmark:
    renderer:
      unsafe: true
